CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(150) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "role" VARCHAR(20) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "candidates" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT UNIQUE NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "cpf" VARCHAR(11) UNIQUE NOT NULL,
  "phone" VARCHAR(15) UNIQUE NOT NULL,
  "professional_summary" TEXT,
  "linkedin_url" VARCHAR(255),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "companies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT UNIQUE NOT NULL,
  "cnpj" VARCHAR(14) UNIQUE NOT NULL,
  "trade_name" VARCHAR(100) NOT NULL,
  "corporate_name" VARCHAR(150) NOT NULL,
  "description" TEXT,
  "website_url" VARCHAR(255),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "experiences" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "candidate_id" BIGINT NOT NULL,
  "company" VARCHAR(100) NOT NULL,
  "job_title" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "start_date" DATE NOT NULL,
  "end_date" DATE
);

CREATE TABLE "skills" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE "candidate_skills" (
  "candidate_id" BIGINT NOT NULL,
  "skill_id" BIGINT NOT NULL,
  "level" VARCHAR(20) NOT NULL,
  PRIMARY KEY ("candidate_id", "skill_id")
);

CREATE TABLE "jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" BIGINT NOT NULL,
  "title" VARCHAR(120) NOT NULL,
  "description" TEXT NOT NULL,
  "requirements" TEXT,
  "salary" DECIMAL(10,2),
  "work_mode" VARCHAR(20) NOT NULL,
  "contract_type" VARCHAR(20) NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ,
  "deleted_at" TIMESTAMPTZ
);

CREATE TABLE "applications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" BIGINT NOT NULL,
  "candidate_id" BIGINT NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "applied_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX "uk_job_candidate" ON "applications" ("job_id", "candidate_id");

-- COMMENTS
COMMENT ON COLUMN "users"."id" IS 'Unique identifier';
COMMENT ON COLUMN "users"."email" IS 'System access email';
COMMENT ON COLUMN "users"."password" IS 'BCrypt password hash';
COMMENT ON COLUMN "users"."role" IS 'Role (CANDIDATE or COMPANY)';
COMMENT ON COLUMN "users"."created_at" IS 'Record creation timestamp';
COMMENT ON COLUMN "users"."updated_at" IS 'Last update timestamp';

COMMENT ON COLUMN "candidates"."id" IS 'Unique identifier';
COMMENT ON COLUMN "candidates"."user_id" IS '1:1 link to users table';
COMMENT ON COLUMN "candidates"."name" IS 'Candidate full name';
COMMENT ON COLUMN "candidates"."cpf" IS 'Digits only';
COMMENT ON COLUMN "candidates"."phone" IS 'Phone number with area code';
COMMENT ON COLUMN "candidates"."professional_summary" IS 'Short profile bio';
COMMENT ON COLUMN "candidates"."linkedin_url" IS 'LinkedIn profile link';
COMMENT ON COLUMN "candidates"."created_at" IS 'Audit log';
COMMENT ON COLUMN "candidates"."updated_at" IS 'Audit log';

COMMENT ON COLUMN "companies"."id" IS 'Unique identifier';
COMMENT ON COLUMN "companies"."user_id" IS '1:1 link to users table';
COMMENT ON COLUMN "companies"."cnpj" IS 'Digits only';
COMMENT ON COLUMN "companies"."trade_name" IS 'Commercial/Trade name';
COMMENT ON COLUMN "companies"."corporate_name" IS 'Registered corporate name';
COMMENT ON COLUMN "companies"."description" IS 'Company presentation';
COMMENT ON COLUMN "companies"."website_url" IS 'Official website';
COMMENT ON COLUMN "companies"."created_at" IS 'Audit log';
COMMENT ON COLUMN "companies"."updated_at" IS 'Audit log';

COMMENT ON COLUMN "experiences"."id" IS 'Unique identifier';
COMMENT ON COLUMN "experiences"."candidate_id" IS 'Belongs to candidate (1:N)';
COMMENT ON COLUMN "experiences"."company" IS 'Company name';
COMMENT ON COLUMN "experiences"."job_title" IS 'Job title / position';
COMMENT ON COLUMN "experiences"."description" IS 'Responsibilities and achievements';
COMMENT ON COLUMN "experiences"."start_date" IS 'Employment start date';
COMMENT ON COLUMN "experiences"."end_date" IS 'Employment end date (null if current)';

COMMENT ON COLUMN "skills"."id" IS 'Unique identifier';
COMMENT ON COLUMN "skills"."name" IS 'Technology or skill name';

COMMENT ON COLUMN "candidate_skills"."candidate_id" IS 'Linked candidate';
COMMENT ON COLUMN "candidate_skills"."skill_id" IS 'Linked skill';
COMMENT ON COLUMN "candidate_skills"."level" IS 'Proficiency level (BEGINNER, INTERMEDIATE, ADVANCED)';

COMMENT ON COLUMN "jobs"."id" IS 'Unique identifier';
COMMENT ON COLUMN "jobs"."company_id" IS 'Company owner (1:N)';
COMMENT ON COLUMN "jobs"."title" IS 'Opportunity title';
COMMENT ON COLUMN "jobs"."description" IS 'Opportunity details';
COMMENT ON COLUMN "jobs"."requirements" IS 'Job requirements';
COMMENT ON COLUMN "jobs"."salary" IS 'Compensation value';
COMMENT ON COLUMN "jobs"."work_mode" IS 'REMOTE, HYBRID, ON_SITE';
COMMENT ON COLUMN "jobs"."contract_type" IS 'CLT, PJ, INTERNSHIP';
COMMENT ON COLUMN "jobs"."status" IS 'OPEN, PAUSED, CLOSED';
COMMENT ON COLUMN "jobs"."created_at" IS 'Publication timestamp';
COMMENT ON COLUMN "jobs"."updated_at" IS 'Last update timestamp';
COMMENT ON COLUMN "jobs"."deleted_at" IS 'Soft Delete timestamp';

COMMENT ON COLUMN "applications"."id" IS 'Unique identifier';
COMMENT ON COLUMN "applications"."job_id" IS 'Target job position';
COMMENT ON COLUMN "applications"."candidate_id" IS 'Applying candidate';
COMMENT ON COLUMN "applications"."status" IS 'RECEIVED, IN_REVIEW, APPROVED, REJECTED';
COMMENT ON COLUMN "applications"."applied_at" IS 'Application timestamp';

-- FOREIGN KEYS (CORRIGIDAS)
ALTER TABLE "candidates" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "companies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "experiences" ADD FOREIGN KEY ("candidate_id") REFERENCES "candidates" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "candidate_skills" ADD FOREIGN KEY ("candidate_id") REFERENCES "candidates" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "candidate_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "jobs" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "applications" ADD FOREIGN KEY ("job_id") REFERENCES "jobs" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "applications" ADD FOREIGN KEY ("candidate_id") REFERENCES "candidates" ("id") DEFERRABLE INITIALLY IMMEDIATE;
